# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '3.0.100-preview5-011568'
# Starter pipeline
- script: dotnet restore ./OAuthDemystifiedTT/OAuthDemystifiedTT.csproj
- script: dotnet restore ./OauthHandler/OauthHandler.csproj
- script: dotnet restore ./WebApitest/WebApitest.csproj
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'
- task: PublishBuildArtifacts@1
