# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# Starter pipeline
- task: DotnetRestore@1
  inputs:
    command: 'restore'
    feedsToUse: 'config'
    projects: '/OAuthDemystifiedTT/OAuthDemystifiedTT.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
