version: '3'

services:
  ci-build:
    image: 3.0.0-preview6-buster-slim
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./OAuthDemystifiedTT.sln && dotnet publish ./OAuthDemystifiedTT.sln -c Release -o ./obj/Docker/publish"
