apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: back
  namespace: mstt-1
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 

  template:
    metadata:      
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: ibmkettkubernetesacr.azurecr.io/webapitest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: back
  namespace: mstt-1
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: back
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: back-ingress
#  namespace:  mstt-1
#  annotations:
#    kubernetes.io/ingress.class: addon-http-application-routing
#spec:  
#  rules:
#  - host: back.0d1459123cdb4220b8b5.westeurope.aksapp.io
#    http:
#      paths:
#      - backend:
#          serviceName: back
#          servicePort: 8080
#        path: /
#---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-front
  namespace: mstt-1
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 

  template:
    metadata:      
      labels:
        app: web-front
    spec:
      containers:
      - name: web-front
        image: ibmkettkubernetesacr.azurecr.io/oauthdemystifiedtt
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"   
        - name: PROTOCOL
          value: "http"
        - name: STORAGE_SECRET
          value: "/iVNlvgYXi5+CtDogwqLkZKX4tunqdPTnEq7yvEDlvWjXSkCNcS44VWsMspufqtjszFXhFz8b6eNylJHdP+BUg=="
        #resources:
        #  requests:
        #    cpu: 250m
        #  limits:
        #    cpu: 500m
      #imagePullSecrets:
      #- name: azacr        
---
apiVersion: v1
kind: Service
metadata:  
  name: msttclusterip
  namespace: mstt-1
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: web-front
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: msttingress
  namespace:  mstt-1
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:  
  rules:
  - host: mstt1.0d1459123cdb4220b8b5.westeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: msttclusterip
          servicePort: 80
        path: /