kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: kube-system
  labels:
    k8s-app: nginx-ingress-controller
data:
  proxy-buffer-size: "128k"
  proxy-buffers: "4 256k"
  large-client-header-buffers: "4 256k"