apiVersion: v1
kind: Service
metadata:
  labels:
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: msttclusterip
  namespace: {{.Values.msttclusterip.namespace}}
spec:
  type: {{.Values.msttclusterip.serviceType}}
  ports:
  - port: 80
  selector:
    app: web-front
