{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.ingress.name}}
  namespace: {{.Values.ingress.namespace}}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $hostIndex, $hostVal := .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:       
      {{- range $index, $val := .paths }}
        - path: {{ $val.path }}
          {{ $val.pathName }}:
            serviceName: {{ $val.serviceName }}
            servicePort: {{ $val.servicePort }}
      {{- end }}
  {{- end }}
{{- end }}
